### ISSUE TITLE
So you guys have a demo?

### ISSUE THREAD

**Issue by iamdinakar** [bartosjiri/discourse-nightfall-theme#1]
And, is it still being developed/maintained?

**Comment by bartosjiri** [comment]
Unfortunately no, the theme is no longer maintained since frequent Discourse updates were causing breaking changes way too often.

You can create a demo for yourself in Discourse's official [Theme Creator](https://theme-creator.discourse.org/).

**Comment by iamdinakar** [comment]
Thanks for your response and I'll check.
